### ISSUE TITLE
Two license files

### ISSUE THREAD

**Issue by ryandesign** [devongarde/ssc#54]
This project contains both [LICENSE.txt](https://github.com/devongarde/ssc/blob/default/LICENSE.txt) and [LICENCE.txt](https://github.com/devongarde/ssc/blob/default/LICENCE.txt) and they are different and this is confusing.

**Comment by devongarde** [comment]
Actually, having both LICENCE.txt and LICENSE.txt is quite deliberate. The names illustrate why ssc exists. The confusion, if it's there, lies in a standards' linguistic mess that ssc attempts to address.

In general, the various standards require dialect spelling ('color' versus 'colour', etc.). However, there are places, such as certain ontologies, that require standard spelling ('centre' versus 'center', etc.). The sensible thing would have been for all those standards and specifications to accept all valid spellings, but few do so.

Thus the use of standard English versus dialect is a mess when you consider the various standards and specifications as a whole. It will catch people out. Given ssc exists to help people who hand code website who want to avoid being caught out, it issues warnings when correct spelling is used but incorrect is required, and vice versa, whatever your concept of correct and incorrect. It does a bit more than that, of course.

Furthermore, I have no intention that ssc, when used, implies that any variant of English is the more important. To quote the OED in 2015, "Another fundamental mistake is to think of the 'standard' variety of a language as the language, with dialects relegated to substandard status" (https://web.archive.org/web/20150317093917/https://public.oed.com/aspects-of-english/english-in-use/english-dialect-study-an-overview/).

Of course, if you look at the code, you'll see it's written in my dialects, but that's a reflection of me, not ssc.

LICENSE.txt, as is, as spelt, is named by convention for the GPL. LICENCE.txt, as spelt, contains all the other licence information, as required by content used in the product. I do not believe I can properly put them into one file, since I gather the GPL licence information should to kept separate and aloof. Hence there are two files. Hence my opportunistic use of the two names to make an important point.

So those two files show the depth to which I've gone to try and help people create less incorrect sites. ssc still alpha, at best, so it's still full of errors. Whether I'll eventually succeed in my goal is a question for the future.

**Comment by devongarde** [comment]
Thus not an issue IMHO.
